version: "3.8"
services:
    frontend: 
        build: 
          context: ./deploy
          dockerfile: Dockerfile
        ports:
            - '80:80'
        volumes:
            - ./frontend/build:/var/www/html
            - ./deploy/default.conf:/etc/nginx/sites-available/default